### ISSUE TITLE
Changes performed on Fraunces as part of the publishing process

### ISSUE THREAD

**Issue by vv-monsalve** [vv-monsalve/Fraunces#2]
This is the summary of changes done on Fraunces a part of the last steps for publishing:

- [x] Changing capitalization for Soften and Wonk names of axes (to meet https://github.com/undercasetype/Fraunces/issues/209#issuecomment-673719201
- [x] Changing the particle of the Soft axis from S000, S050, and S100 to Sharp, Soft, Extra Soft respectively (to meet https://github.com/undercasetype/Fraunces/issues/209#issuecomment-690836666)
- [x] After done that, it created some conflicts that led to both Fails or  Errors when using some scripts from Yanone, so I gradually started to stop using them (after try/error attempts).
- [x] I've been struggling particularly with the Italics, as for some reason the name ID2 was kept in "Regular", thus leading to a fail.
- [x] After many fixes from the designspace I went to .ufo files and made some changes as I would have done in Glyphs sources (after understanding better the ufo sources on Robofont), leaving only "weight" axis information in the StyleName and specifying the usWidthClass and usWeightClass in the Opentype OS/2 Table info.
As It didn't solve the name ID 2 (which remain in Regular) so I later deleted the "Black" particle from the StyleName, and it worked to set the name ID 2 to Italic.
- [x] Fixing the Unicode for the glyph 'grave' as it was reported missing but was in the source files
- [x] I changed the default value of the opsz axis to solve this https://github.com/undercasetype/Fraunces/issues/208
- [x] I added the Designers names, URL, and manufacturer to the font info because it was missing, despite no Fail was reported on that at this point.

----

After this process, the current status is:

- `Fraunces-Italic[SOFT,WONK,opsz,wght].tt`f [2 Fails reported](https://github.com/vv-monsalve/Fraunces/blob/QA-Fraunces/fonts/qaFraunces-Vf-it-05.md) 
- `Fraunces[SOFT,WONK,opsz,wght].ttf` [2 Fails reported](https://github.com/vv-monsalve/Fraunces/blob/QA-Fraunces/fonts/qaFraunces-Vf-10.md)
- Static Fonts: [6 fails reported](https://github.com/vv-monsalve/Fraunces/tree/QA-Fraunces/fonts/static/ttf/Static-fonts_latest_QA_reports) on each subfamily regarding "🔥 FAIL: Check Google Fonts Latin Core glyph coverage."

----

What would be remaining, or what was on my To Do list:

- [ ] Figure out how to solve the remaining fails. 
- [ ] Either report to the designer the missing glyphs or see if they are Unicode cases also and solve them.
- [ ] Adding OTF to the produced font files
- [ ] Simplify and clean the build script file.
- [ ] Create a new .py to add the STAT table, following either what was done in Cabin or Robofont

- - -

Latest files are on my [QA-Fraunces](https://github.com/vv-monsalve/Fraunces/tree/QA-Fraunces) branch

**Comment by vv-monsalve** [comment]
Note: The last point in the ToDo list would be more out of the interest of simplifying it. But it is working, and Fraunces VFs look pretty well in Samsa actually.

**Comment by arrowtype** [comment]
Thanks for all your hard work here, and for the documentation of it as well! I think that’ll make it a lot faster to get it over the final few hurdles.
